# Generated by Django 3.1.1 on 2020-10-01 03:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0004_auto_20201001_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='links',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 3, 55, 27, 91445, tzinfo=utc)),
        ),
    ]
